export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$HOME/.npm-global/bin:$PATH"
export LC_ALL="en_US.UTF-8"
export TERMINAL="kitty"
export EDITOR="nvim"
export VISUAL="nvim"
export FZF_DEFAULT_COMMAND="fd --type f"
export BAT_THEME="ansi"
