add_newline = false

format="""\
	$directory\
	$git_status\
	$character\
"""

right_format="""\
	$cmd_duration\
	$time\
"""

[directory]
truncation_length = 5
truncation_symbol = ".../"
truncate_to_repo = false
format = "[$path]($style)"
style = "cyan"

[git_status]
format = "( [\\[$all_status$ahead_behind\\]]($style))"
style = "cyan"

[character]
format = " $symbol "
success_symbol = "[=>](cyan)"
error_symbol = "[=>](red)"
vicmd_symbol = "[<-](yellow)"

[cmd_duration]
format = "[\\($duration\\)]($style) "
style = "cyan"

[time]
disabled = false
time_format = "%F %R"
format = "[$time]($style)"
style = "cyan"
