add_newline = false

format="""\
	$time\
	$directory\
	$git_branch\
	$git_status\
	$character\
	"""

[time]
disabled = false
format = "\\[[$time]($style)\\]"
time_format = "%T"

[directory]
format = "\\[[$path]($style)\\]"
style = "cyan"

[git_branch]
format = " [$symbol$branch]($style)"

[git_status]
format = "( [\\[$all_status$ahead_behind\\]]($style))"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"

[character]
format = " $symbol "
