add_newline = false

format="""\
	$time\
	$directory\
	$git_branch\
	$git_status\
	$character\
	"""

[time]
disabled = false
format = "\\[[$time]($style)\\]"
style = "yellow"
time_format = "%T"

[directory]
format = "\\[[$path]($style)\\]"
style = "green"

[git_branch]
format = " [$symbol$branch]($style)"
# style = "#ecf0c1"
style = "bright-white"

[git_status]
format = "( [\\[$all_status$ahead_behind\\]]($style))"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"

[character]
format = " $symbol "
success_symbol = "[=>](green)"
error_symbol = "[=>](red)"
vicmd_symbol = "[<-](yellow)"
