vim.keymap.set("n", "]c", [[&diff ? "]c" : "<Cmd>lua require('gitsigns').next_hunk()<CR>"]], { expr = true })
vim.keymap.set("n", "[c", [[&diff ? "[c" : "<Cmd>lua require('gitsigns').prev_hunk()<CR>"]], { expr = true })
vim.keymap.set("n", "<Leader>b", "<Cmd>lua require('gitsigns').blame_line()<CR>")
vim.keymap.set({ "n", "v" }, "<Leader>hs", "<Cmd>lua require('gitsigns').stage_hunk()<CR>")
vim.keymap.set("n", "<Leader>hu", "<Cmd>lua require('gitsigns').undo_stage_hunk()<CR>")
vim.keymap.set("n", "<Leader>hr", "<Cmd>lua require('gitsigns').reset_hunk()<CR>")
vim.keymap.set("n", "<Leader>hR", "<Cmd>lua require('gitsigns').reset_buffer()<CR>")
vim.keymap.set("n", "<Leader>hp", "<Cmd>lua require('gitsigns').preview_hunk()<CR>")
vim.keymap.set("n", "<Leader>sh", "<Cmd>lua require('gitsigns').setqflist()<CR>")
