vim.g.mapleader = " "
vim.g.maplocalleader = " "

vim.keymap.set({ "n", "v" }, "<Leader>", "<Nop>")
vim.keymap.set("n", "U", "<C-r>")
vim.keymap.set("n", "<Leader>w", "<C-w>")
vim.keymap.set("v", "<", "<gv")
vim.keymap.set("v", ">", ">gv")
vim.keymap.set("n", "<C-Down>", "<Cmd>move .+1<CR>==zz")
vim.keymap.set("n", "<C-Up>", "<Cmd>move .-2<CR>==zz")
vim.keymap.set("i", "<C-Down>", "<Esc><Cmd>move .+1<CR>==a")
vim.keymap.set("i", "<C-Up>", "<Esc><Cmd>move .-2<CR>==a")
vim.keymap.set("v", "<C-Down>", ":move '>+1<CR>gv=gvzz", { silent = true })
vim.keymap.set("v", "<C-Up>", ":move '<-2<CR>gv=gvzz", { silent = true })
vim.keymap.set("n", "<Esc>", "<Cmd>noh<CR><Esc>")
vim.keymap.set("n", "n", "nzz")
vim.keymap.set("n", "N", "Nzz")
vim.keymap.set("n", "<C-i>", "<C-i>zz")
vim.keymap.set("n", "<C-o>", "<C-o>zz")
vim.keymap.set("n", "<Leader>nt", "gt")
vim.keymap.set("n", "<Leader>cd", "<Cmd>cd %:p:h<CR><Cmd>echo 'Set working directory to:' expand('%:p:h')<CR>")
vim.keymap.set("n", "<F12>", "<Cmd>setlocal spell!<CR>")
